#!/bin/bash

# Alias to use directly as git alias

alias g="git"
alias gst="git status"
alias gpom="git pull origin master"
alias gdf="git diff"
alias gch="git checkout"
alias gchb="git checkout -b"
alias gac="git add . && git commit"
alias grs="git restore staged"
alias gre="git restore"
alias gcl="git clone"
alias glgg="git log --graph --abbrev-commit --decorate --format=fotmat:'%C(bold green)%h%C(reset) - %C(cold cyan)%aD%C(reset) %C(bold yellow)(%ar)%C(reset)%C(auto)%%d%C(reset)%n''		%C(white)%s%C(reset)		%C(dim white)- %an%C(reset)' --all"
alias gmr="git merge"
alias gfc="git fetch"
alias gbr="git branch"
alias glg="git log"
alias gkp='touch .gitkeep; echo " > file .gitkeep created"'
alias gdf="git diff"
alias ggb="# uDev: git global"
alias gbr="# uDev: Change branch"
alias gfv="# uDev: List favoutite commands"
alias gst="git stash" # When local has 1 commit and remote has 1 commit and now you cannot pull nor push. First you stash, than pull, then git stash apply, then push
alias gsa="git stash apply" 

alias gcm="git commit -m"
alias gcm="git commit"
#alias gcm="git commit"
#alias gcmm="git commit -m"

#  "gad"
#     # Git add ...
#  
#  "multi"
#     # Git commit multiple messages
#  
#  "g-ad-cm-m-pu"
#  	# 'git add --all' + 'git commim -m "" ' + 'git push'


